language: node_js
node_js:
  - "iojs"
  - "7"
cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_clean_up: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    local_dir: .deploy_git